"""
Database of proven viral hook formulas, categorized by type.
Based on analysis of top-performing Instagram content.
"""

HOOK_FORMULAS = {
    "curiosity_gap": {
        "label": "Curiosity Gap",
        "description": "Creates an information gap that makes viewers desperate to know the answer.",
        "score_weight": 0.95,
        "templates": [
            "Nobody talks about {topic} but it changed my {outcome}",
            "I found out why {common_thing} is actually {unexpected_truth}",
            "The real reason {topic} doesn't work for you",
            "What happens when you {action} for 30 days straight",
            "I tested {thing} so you don't have to. Here's what happened",
            "The {topic} trick that {authority} don't want you to know",
            "Stop {common_action} — do this instead",
            "This {topic} hack is almost illegal",
            "I've been doing {thing} wrong my entire life",
            "Why {percentage}% of people fail at {topic}",
            "The dark side of {popular_thing} nobody mentions",
            "I accidentally discovered the secret to {outcome}",
        ],
    },
    "contrarian": {
        "label": "Contrarian / Hot Take",
        "description": "Goes against common belief. Triggers engagement through disagreement.",
        "score_weight": 0.90,
        "templates": [
            "{Popular_advice} is the worst advice I've ever heard",
            "Unpopular opinion: {topic} is completely overrated",
            "{Common_thing} is a scam. Here's proof",
            "I stopped {common_action} and everything changed",
            "Everyone is wrong about {topic}",
            "{Popular_thing} is actually ruining your {outcome}",
            "Hot take: {opinion}",
            "I'm going to get hate for this but {statement}",
            "The {topic} industry doesn't want you to see this",
            "Controversial but {topic} is not what you think",
        ],
    },
    "story": {
        "label": "Story Hook",
        "description": "Opens with a compelling personal narrative. Highest watch time.",
        "score_weight": 0.92,
        "templates": [
            "3 years ago I was {bad_situation}. Today I {good_outcome}",
            "I went from {start} to {end} in {timeframe}. Here's how",
            "The moment I realized {realization} everything changed",
            "I lost everything because of {mistake}. Don't repeat this",
            "A stranger told me {advice} and it was the best advice ever",
            "This one decision made me {outcome} in {timeframe}",
            "I was {age} when I figured out {lesson}",
            "My biggest failure taught me {lesson}",
            "I quit my {job} to {action}. {timeframe} later...",
            "Someone asked me {question}. My answer surprised them",
        ],
    },
    "listicle": {
        "label": "Listicle / Number",
        "description": "Numbered lists signal clear value. High save rates.",
        "score_weight": 0.85,
        "templates": [
            "{Number} {topic} mistakes that are costing you {outcome}",
            "{Number} things I wish I knew before {action}",
            "Top {number} {topic} tips that actually work in {year}",
            "{Number} {topic} hacks under {time} minutes",
            "{Number} free {tools} that replaced my ${amount}/month subscriptions",
            "Save this: {number} {topic} rules to live by",
            "{Number} signs you're {situation} (and how to fix it)",
            "The only {number} {things} you need for {outcome}",
            "{Number} {topic} trends to watch in {year}",
            "I tried {number} {things}. Only {smaller_number} were worth it",
        ],
    },
    "authority": {
        "label": "Authority / Proof",
        "description": "Establishes credibility immediately. Builds trust fast.",
        "score_weight": 0.88,
        "templates": [
            "As a {profession} with {years} years of experience, here's the truth about {topic}",
            "I've {achievement} and this is what I learned",
            "After working with {number}+ {clients}, I noticed this pattern",
            "I've spent ${amount} on {topic} so you don't have to",
            "After {number} hours of research, here's what actually works",
            "I {impressive_feat}. Here's my exact {strategy}",
            "My {topic} went from {start} to {end}. The strategy is simple",
            "{Number} years in {industry} taught me one thing",
            "I've helped {number}+ people {outcome}. The secret is {hook}",
            "Coming from someone who {credential}: {statement}",
        ],
    },
    "fear_urgency": {
        "label": "Fear / Urgency",
        "description": "Triggers loss aversion. Creates FOMO. High click-through.",
        "score_weight": 0.87,
        "templates": [
            "If you're not doing {action} in {year}, you're falling behind",
            "This {thing} is about to change everything. Are you ready?",
            "You're losing {outcome} every day you ignore {topic}",
            "Warning: {topic} is not what it used to be",
            "{Thing} is dying. Here's what's replacing it",
            "Last chance to {action} before {event}",
            "The {topic} bubble is about to burst",
            "Most people won't see this coming: {prediction}",
            "If you {action}, stop immediately. Here's why",
            "The clock is ticking on {topic}. Here's what to do now",
        ],
    },
    "value_promise": {
        "label": "Value Promise",
        "description": "Promises clear, specific value upfront. High save rate.",
        "score_weight": 0.86,
        "templates": [
            "Save this for later: the complete guide to {topic}",
            "The only {topic} tutorial you'll ever need",
            "How to {outcome} in {timeframe} (step by step)",
            "Free {resource} that will {outcome} (link in bio)",
            "The exact {strategy} I used to {outcome}",
            "Here's your {topic} cheat sheet",
            "Copy my exact {thing} for {outcome}",
            "Steal my {topic} template (it's free)",
            "The simplest way to {outcome} — explained in {time}",
            "Watch this before you {action}. It'll save you {time/money}",
        ],
    },
    "question": {
        "label": "Question Hook",
        "description": "Engages the brain automatically. People can't resist answering.",
        "score_weight": 0.83,
        "templates": [
            "What would you do if {scenario}?",
            "Can you actually {outcome} by just {simple_action}?",
            "Why does nobody talk about {topic}?",
            "Is {popular_thing} actually worth it in {year}?",
            "What's the worst {topic} advice you've ever received?",
            "Did you know that {surprising_fact}?",
            "Are you making this {topic} mistake?",
            "What if everything you knew about {topic} was wrong?",
            "Want to know the fastest way to {outcome}?",
            "How do {successful_people} {action} so easily?",
        ],
    },
}

NICHES = [
    "fitness", "finance", "marketing", "tech", "cooking",
    "travel", "fashion", "beauty", "productivity", "mindset",
    "business", "real estate", "crypto", "health", "parenting",
    "photography", "music", "gaming", "education", "self-improvement",
    "ai & tools", "side hustles", "motivation", "relationships", "career",
]

POWER_WORDS = [
    "secret", "proven", "free", "instant", "guaranteed", "exclusive",
    "shocking", "hack", "ultimate", "insane", "brutal", "deadly",
    "powerful", "hidden", "banned", "illegal", "truth", "exposed",
    "genius", "underrated", "game-changer", "life-changing", "viral",
    "simple", "easy", "fast", "overnight", "effortless", "no one",
    "everyone", "stop", "never", "always", "warning", "mistake",
    "finally", "actually", "literally", "seriously", "honestly",
]

EMOTIONAL_TRIGGERS = {
    "curiosity": ["secret", "hidden", "truth", "exposed", "real reason", "nobody", "actually", "find out"],
    "fear": ["warning", "mistake", "stop", "never", "losing", "dying", "falling behind", "dangerous"],
    "greed": ["free", "money", "income", "passive", "rich", "profit", "cash", "earn", "revenue"],
    "urgency": ["now", "today", "hurry", "last chance", "before", "limited", "running out", "immediately"],
    "social_proof": ["everyone", "million", "thousands", "viral", "trending", "top", "best", "proven"],
    "aspiration": ["dream", "freedom", "success", "lifestyle", "achieve", "transform", "level up", "upgrade"],
}
